# ===============================
# BANCO POSTGRES - SUPABASE (SAO PAULO)
# ===============================

db.vendor=postgres

db.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require

db.user=postgres.tmwgnfgtmvomdecpblgh
db.password=Lhv7xSNdPKlwjHZq


# ===============================
# CONFIGURACAO DO POOL
# ===============================

pool.max=10
pool.minIdle=2
pool.connectionTimeoutMs=10000
pool.idleTimeoutMs=120000
pool.maxLifetimeMs=1800000