# ===============================
# BANCO POSTGRES - SUPABASE (SAO PAULO)
# ===============================

db.vendor=postgres

db.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require

db.user=postgres.tmwgnfgtmvomdecpblgh
db.password=Lhv7xSNdPKlwjHZq


# ===============================
# CONFIGURACAO DO POOL
# ===============================

pool.max=10
pool.minIdle=2
pool.connectionTimeoutMs=10000
pool.idleTimeoutMs=120000
pool.maxLifetimeMs=1800000


# ===============================
# SUPABASE STORAGE
# ===============================

supabase.url=https://tmwgnfgtmvomdecpblgh.supabase.co
supabase.service_role_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtd2duZmd0bXZvbWRlY3BibGdoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjUwMDk0MSwiZXhwIjoyMDg4MDc2OTQxfQ.GGlxftzbOvu4i1_kUGBJiG8loIwVoZn35xBI-GuMMUM
supabase.bucket=anexos
supabase.signed_url_seconds=600