package br.com.clinica.dao;

import br.com.clinica.database.DatabaseConfig;
import br.com.clinica.model.enums.SalaAtendimento;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Types;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.atomic.AtomicBoolean;

public class ProcedimentoFrequenteDAO {

    private static final Locale LOCALE_PT_BR = Locale.forLanguageTag("pt-BR");
    private static final DateTimeFormatter DB_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss", LOCALE_PT_BR);

    // ✅ garante que DDL rode no máximo 1x por execução do app
    private static final AtomicBoolean INIT_DONE = new AtomicBoolean(false);

    public ProcedimentoFrequenteDAO() {
        garantirTabelaUmaVez();
    }

    private void garantirTabelaUmaVez() {
        if (INIT_DONE.get()) return;

        synchronized (ProcedimentoFrequenteDAO.class) {
            if (INIT_DONE.get()) return;

            try (Connection c = DatabaseConfig.getConnection()) {
                boolean pg = isPostgres(c);

                // ⚠️ Em produção (Postgres/Supabase), o ideal é criar isso via migrations no Supabase,
                // não pelo app. Mas para manter seu comportamento "automático" sem ficar lento,
                // fazemos só 1 vez por execução.
                garantirTabela(c, pg);

                INIT_DONE.set(true);
            } catch (Exception e) {
                throw new RuntimeException("Erro ao garantir tabela de procedimentos frequentes", e);
            }
        }
    }

    private void garantirTabela(Connection c, boolean pg) throws Exception {
        final String sqlSqlite = """
            CREATE TABLE IF NOT EXISTS procedimento_frequente (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              nome TEXT NOT NULL,
              sala TEXT,
              uso_count INTEGER NOT NULL DEFAULT 0,
              ultimo_uso TEXT NOT NULL,
              UNIQUE(nome, sala)
            );
        """;

        final String sqlPostgres = """
            CREATE TABLE IF NOT EXISTS procedimento_frequente (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              nome TEXT NOT NULL,
              sala TEXT,
              uso_count INTEGER NOT NULL DEFAULT 0,
              ultimo_uso TEXT NOT NULL,
              UNIQUE(nome, sala)
            );
        """;

        // índice para ordenar por sala/uso/último uso (ajuda muito as sugestões)
        final String idx = """
            CREATE INDEX IF NOT EXISTS idx_proc_freq_sala_uso
            ON procedimento_frequente(sala, uso_count DESC, ultimo_uso DESC);
        """;

        try (PreparedStatement ps = c.prepareStatement(pg ? sqlPostgres : sqlSqlite);
             PreparedStatement ps2 = c.prepareStatement(idx)) {
            ps.execute();
            ps2.execute();
        }
    }

    private boolean isPostgres(Connection c) {
        try {
            String prod = c.getMetaData().getDatabaseProductName();
            return prod != null && prod.toLowerCase().contains("postgres");
        } catch (Exception e) {
            return false;
        }
    }

    public void registrarUso(String nomeProcedimento, SalaAtendimento sala) {
        String nome = normalizar(nomeProcedimento);
        if (nome.isBlank()) return;

        String salaStr = (sala == null) ? null : sala.name();
        String agora = LocalDateTime.now().format(DB_FMT);

        String upsert = """
            INSERT INTO procedimento_frequente (nome, sala, uso_count, ultimo_uso)
            VALUES (?, ?, 1, ?)
            ON CONFLICT(nome, sala)
            DO UPDATE SET uso_count = procedimento_frequente.uso_count + 1,
                          ultimo_uso = EXCLUDED.ultimo_uso;
        """;

        try (Connection c = DatabaseConfig.getConnection();
             PreparedStatement ps = c.prepareStatement(upsert)) {

            ps.setString(1, nome);

            if (salaStr == null) ps.setNull(2, Types.VARCHAR);
            else ps.setString(2, salaStr);

            ps.setString(3, agora);
            ps.executeUpdate();

        } catch (Exception e) {
            throw new RuntimeException("Erro ao registrar uso de procedimento", e);
        }
    }

    public List<String> sugerir(String digitado, SalaAtendimento sala, int limite) {
        String t = (digitado == null) ? "" : digitado.trim();
        String salaStr = (sala == null) ? null : sala.name();

        List<String> out = new ArrayList<>();
        if (t.isBlank()) return out;

        // ✅ No Postgres use ILIKE (mais simples e evita LOWER(nome))
        // ✅ No SQLite mantém LOWER(nome) LIKE
        String sqlPg = """
            SELECT nome
            FROM procedimento_frequente
            WHERE (? IS NULL OR sala = ? OR sala IS NULL)
              AND (nome ILIKE ?)
            ORDER BY
              CASE WHEN sala = ? THEN 0
                   WHEN sala IS NULL THEN 1
                   ELSE 2 END,
              uso_count DESC,
              ultimo_uso DESC
            LIMIT ?;
        """;

        String sqlSqlite = """
            SELECT nome
            FROM procedimento_frequente
            WHERE (? IS NULL OR sala = ? OR sala IS NULL)
              AND (LOWER(nome) LIKE ?)
            ORDER BY
              CASE WHEN sala = ? THEN 0
                   WHEN sala IS NULL THEN 1
                   ELSE 2 END,
              uso_count DESC,
              ultimo_uso DESC
            LIMIT ?;
        """;

        try (Connection c = DatabaseConfig.getConnection()) {
            boolean pg = isPostgres(c);
            String sql = pg ? sqlPg : sqlSqlite;

            try (PreparedStatement ps = c.prepareStatement(sql)) {

                if (salaStr == null) {
                    ps.setNull(1, Types.VARCHAR);
                    ps.setNull(2, Types.VARCHAR);
                } else {
                    ps.setString(1, salaStr);
                    ps.setString(2, salaStr);
                }

                String like = "%" + (pg ? t : t.toLowerCase(LOCALE_PT_BR)) + "%";
                ps.setString(3, like);

                if (salaStr == null) ps.setNull(4, Types.VARCHAR);
                else ps.setString(4, salaStr);

                ps.setInt(5, Math.max(1, limite));

                var rs = ps.executeQuery();
                while (rs.next()) {
                    out.add(rs.getString("nome"));
                }
            }

        } catch (Exception e) {
            throw new RuntimeException("Erro ao sugerir procedimentos frequentes", e);
        }

        return out;
    }

    public String normalizar(String s) {
        if (s == null) return "";
        return s.trim().replaceAll("\\s+", " ");
    }
}